# Generated by Django 5.0.6 on 2024-07-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdashboard', '0002_auto_20240711_1919'),
    ]

    operations = [
    ]
